plugins {
    id("com.gradleup.shadow") version "8.3.7"
    id("io.micronaut.application") version "4.5.4"
    id("io.micronaut.aot") version "4.5.4"
}

version getProperty("projectVersion")
group = "coop.stlma.tech.protocolsn"

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")

    //web
    annotationProcessor("io.micronaut:micronaut-http-validation")
    implementation("io.micronaut:micronaut-http-client")
    testImplementation("io.micronaut:micronaut-http-client")
    annotationProcessor("io.micronaut:micronaut-http-validation")
    implementation("io.micronaut.validation:micronaut-validation")

    //client
    implementation("io.micronaut.views:micronaut-views-fieldset")
    implementation("io.micronaut.views:micronaut-views-thymeleaf")

    //protocol-sn
    implementation("coop.stlma.tech.protocolsn:keycloak-api:0.3.3")
    implementation("coop.stlma.tech.protocolsn:plugin-lib:0.5.0")
    implementation("coop.stlma.tech.protocolsn:common-lib:0.5.0")
    implementation("coop.stlma.tech.protocolsn:user-plugin-api:0.4.2")

    //serde
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    implementation("io.micronaut.serde:micronaut-serde-jackson")

    //reactor
    implementation("io.micronaut.reactor:micronaut-reactor")

    //web
    compileOnly("io.micronaut:micronaut-http-client")
    annotationProcessor("io.micronaut:micronaut-http-validation")

    //logging
    runtimeOnly("ch.qos.logback:logback-classic")

    //properties
    runtimeOnly("org.yaml:snakeyaml")

    //security
    annotationProcessor("io.micronaut.security:micronaut-security-annotations")
    implementation("io.micronaut.security:micronaut-security-oauth2")
    implementation("io.micronaut.security:micronaut-security-jwt")

    //swagger
    annotationProcessor("io.micronaut.openapi:micronaut-openapi")
    implementation("io.micronaut.openapi:micronaut-openapi-annotations")

    //testing
    testImplementation("io.micronaut:micronaut-http-client")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
    testImplementation("org.junit.jupiter:junit-jupiter-engine")
    testAnnotationProcessor("io.micronaut:micronaut-inject-java")
    testImplementation("org.mockito:mockito-core")
    testImplementation("io.projectreactor:reactor-test")
}


application {
    mainClass = "coop.stlma.tech.protocolsn.userplugin.Application"
}
java {
    sourceCompatibility = JavaVersion.toVersion("21")
    targetCompatibility = JavaVersion.toVersion("21")
}


graalvmNative.toolchainDetection = false
micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("coop.stlma.tech.protocolsn.*")
    }
    aot {
    // Please review carefully the optimizations enabled below
    // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
        replaceLogbackXml = true
    }
}


tasks.named("dockerfileNative") {
    jdkVersion = "21"
}


