micronaut:
  server:
    port: 8080
    context-path: /user
  http:
    services:
      keycloak-admin:
        url: http://${KEYCLOAK_HOST}/
  security:
    oauth2:
      clients:
        keycloak:
          client-secret: ${USER_PLUGIN_CLIENT_SECRET}
          openid:
            issuer: https://${KEYCLOAK_HOST}/realms/social-network-ecosystem

coop:
  stlma:
    tech:
      protocolsn:
        plugin-name: ProtocolSNUserPlugin
        plugin-target: dns:///${USER_PLUGIN_HOST}:${USER_PLUGIN_GRPC_PORT}

grpc:
  server:
    port: ${USER_PLUGIN_GRPC_PORT}
  channels:
    node-manager:
      address: ${NODE_MANAGER_HOST}
      plaintext: true
