micronaut:
  server:
    port: 8080
    context-path: /user
  http:
    services:
      keycloak-admin:
        url: http://${KEYCLOAK_HOST}/
  security:
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: http://${KEYCLOAK_HOST}/realms/social-network-ecosystem/protocol/openid-connect/certs
    oauth2:
      clients:
        local-keycloak:
          client-secret: ${USER_PLUGIN_CLIENT_SECRET}
          openid:
            issuer: http://${KEYCLOAK_HOST}/realms/social-network-ecosystem
        keycloak-client:
          client-secret: ${USER_PLUGIN_CLIENT_SECRET}
          token:
            url: http://${KEYCLOAK_HOST}/realms/social-network-ecosystem/protocol/openid-connect/token
          client-credentials:
            service-id-regex: keycloak-admin
          openid:
            issuer: http://${KEYCLOAK_HOST}/realms/social-network-ecosystem

coop:
  stlma:
    tech:
      protocolsn:
        plugin-name: ProtocolSNUserPlugin
        plugin-target: dns:///${USER_PLUGIN_HOST}:${USER_PLUGIN_GRPC_PORT}

grpc:
  server:
    port: ${USER_PLUGIN_GRPC_PORT}
  channels:
    node-manager:
      address: ${NODE_MANAGER_HOST}
      plaintext: true
