micronaut:
  server:
    port: 8080
    context-path: /user
  security:
    oauth2:
      clients:
        keycloak:
          openid:
            issuer: http://localhost:5005/realms/social-network-ecosystem
        keycloak-client:
          token:
            url: http://localhost:5005/realms/social-network-ecosystem/protocol/openid-connect/token
          openid:
            issuer: http://localhost:5005/realms/social-network-ecosystem

coop:
  stlma:
    tech:
      protocolsn:
        plugin-name: ProtocolSNUserPlugin
        plugin-target: dns:///psn-user-plugin:50051

grpc:
  server:
    port: 50051
  channels:
    node-manager:
      target: psn-node-manager:50051
      plaintext: true
